# Generated by Django 3.2.6 on 2021-08-25 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_formation', '0003_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
